---
title: "Informe Consultoria"
author: "Luis Hernández y Juan Carvajal"
format: pdf
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false


## Paquetes usados 
library(tidyverse)
library(readxl)
library(janitor)
require(magrittr)
require(ggplot2)
require(vcd)
require(corrplot)
require(RColorBrewer)
```

```{r}
#| echo: false


# cargando la base de datos
bd <- read_excel("BDD.Análisis_PD-L1_26-09-2024.xlsx", sheet = "BD_330")

# limpiando los nombres de las variables

bd <- clean_names(bd)
```

```{r}
#| echo: false

# convirtiendo variables tipo factor
bd$codigo <- as.factor(bd$codigo)
bd$estado_vital_5años <- as.factor(bd$estado_vital_5anos)
bd$estado_vital_2 <- as.factor(bd$estado_vital_2)
bd$ciudad <- as.factor(bd$ciudad)
bd$edad_cat <- as.factor(bd$edad_cat)
bd$edad_cat2 <- as.factor(bd$edad_cat2)
bd$estrato <- as.factor(bd$estrato)
bd$estrato_cat <- as.factor(bd$estrato_cat)
bd$educacion <- as.factor(bd$educacion)
bd$educacion_cat <- as.factor(bd$educacion_cat)
bd$afiliacion <- as.factor(bd$afiliacion)
bd$lateralidad_cat <- as.factor(bd$lateralidad_cat)
bd$tipo_histologico <- as.factor(bd$tipo_histologico)
bd$tipo_histol_cat <- as.factor(bd$tipo_histol_cat)
bd$grado_histologico <- as.factor(bd$grado_histologico)
bd$grado_nuclear <- as.factor(bd$grado_nuclear)
bd$gh_gn <- as.factor(bd$gh_gn)
bd$t <- as.factor(bd$t)
bd$n <- as.factor(bd$n)
bd$m <- as.factor(bd$m)
bd$estadio <- as.factor(bd$estadio)
bd$estadio_cat <- as.factor(bd$estadio_cat)
bd$estadio_cat3 <- as.factor(bd$estadio_cat3)
bd$estadio_early_late <- as.factor(bd$estadio_early_late)
bd$er <- as.factor(bd$er)
bd$pr <- as.factor(bd$pr)
bd$her2 <- as.factor(bd$her2)
bd$subtipo_molecular_definitivo <- as.factor(bd$subtipo_molecular_definitivo)
bd$eur_cat <- as.factor(bd$eur_cat)
bd$nam_cat <- as.factor(bd$nam_cat)
bd$afr_cat <- as.factor(bd$afr_cat)
bd$recaidas <- as.factor(bd$recaidas)
bd$ano_dx <- as.factor(bd$ano_dx)
bd$cuartil_fecha_dx <- as.factor(bd$cuartil_fecha_dx)
bd$pd_l1 <- as.factor(bd$pd_l1)
bd$interaccion_reg_stage <- as.factor(bd$interaccion_reg_stage)
```


```{r}
#| include: false
#| echo: false

Datos <- read_excel("BDD.Análisis_PD-L1_26-09-2024.xlsx",sheet = "BD_330")

Datos$codigo <- as.factor(Datos$codigo)
Datos$estado_vital_5años <- as.factor(Datos$estado_vital_5años)
Datos$estado_vital_2 <- as.factor(Datos$estado_vital_2)
Datos$ciudad <- as.factor(Datos$ciudad)
Datos$edad_cat <- as.factor(Datos$edad_cat)
Datos$`edad-cat2` <- as.factor(Datos$`edad-cat2`)
Datos$estrato <- as.factor(Datos$estrato)
Datos$estrato_cat <- as.factor(Datos$estrato_cat)
Datos$educacion <- as.factor(Datos$educacion)
Datos$educacion_cat <- as.factor(Datos$educacion_cat)
Datos$afiliacion <- as.factor(Datos$afiliacion)
Datos$lateralidad_cat <- as.factor(Datos$lateralidad_cat)
Datos$tipo_histologico <- as.factor(Datos$tipo_histologico)
Datos$tipo_histol_cat <- as.factor(Datos$tipo_histol_cat)
Datos$grado_histologico <- as.factor(Datos$grado_histologico)
Datos$grado_nuclear <- as.factor(Datos$grado_nuclear)
Datos$`gh/gn` <- as.factor(Datos$`gh/gn`)
Datos$T <- as.factor(Datos$T)
Datos$N <- as.factor(Datos$N)
Datos$M <- as.factor(Datos$M)
Datos$estadio <- as.factor(Datos$estadio)
Datos$estadio_cat <- as.factor(Datos$estadio_cat)
Datos$estadio_cat3 <- as.factor(Datos$estadio_cat3)
Datos$`estadio-Early_late` <- as.factor(Datos$`estadio-Early_late`)
Datos$ER <- as.factor(Datos$ER)
Datos$PR <- as.factor(Datos$PR)
Datos$HER2 <- as.factor(Datos$HER2)
Datos$subtipo_molecular_definitivo <- as.factor(Datos$subtipo_molecular_definitivo)
Datos$EUR_cat <- as.factor(Datos$EUR_cat)
Datos$NAM_cat <- as.factor(Datos$NAM_cat)
Datos$AFR_cat <- as.factor(Datos$AFR_cat)
Datos$recaidas <- as.factor(Datos$recaidas)
Datos$`Año dx` <- as.factor(Datos$`Año dx`)
Datos$`Cuartil_fecha dx` <- as.factor(Datos$`Cuartil_fecha dx`)
Datos$`PD-L1` <- as.factor(Datos$`PD-L1`)
Datos$`Interacción_Reg/stage` <- as.factor(Datos$`Interacción_Reg/stage`)
```



# Análisis Descriptivo

## Correlaciones entre las variables 

```{r}
#| fig-width: 10
#| fig-height: 15
#| fig-align: center
# Mirar correlaciones entre las variables

# Función para calcular Cramer's V entre dos variables
cramerV <- function(var1, var2) {
  tabla <- table(var1, var2)
  assocstats(tabla)$cramer
}

Datos1 <- Datos %>% select_if(is.factor) %>% select(-c('PD-L1','codigo'))

# Función para crear una matriz de Cramer's V
cramerV_matrix <- function(data) {
  n <- ncol(data)
  mat <- matrix(NA, n, n)
  colnames(mat) <- rownames(mat) <- colnames(data)
  for (i in 1:n) {
    for (j in 1:n) {
      if(i==j){
        mat[i,j] <- 1
      }else if (is.nan(cramerV(data[[i]],data[[j]]))) {
        mat[i,j] <-- 0
      }else{
        mat[i, j] <- cramerV(data[[i]], data[[j]])
      }
    }
  }
  return(mat)
}

corrplot(cramerV_matrix(Datos1),method = "circle",type = "upper")
```

## Analisis descritivos de variables individuales

```{r}
#| fig-align: center
#| layout-ncol: 4
#| layout-nrow: 5
#| warning: false

# Análisis descriptivos de las variables mas relevantes con la respuesta

variables <- c('estado_vital_5años','estado_vital_2','ciudad','estrato','T','afiliacion','tipo_histologico','T','N','M','estadio','estadio_cat','estadio_cat3',
               'estadio-Early_late','ER','PR','subtipo_molecular_definitivo','recaidas',
               'Interacción_Reg/stage')

# variables individuales

# Bucle para crear un gráfico de barras por variable
for (var in variables) {
  Datos1[[var]] %>% table() %>% barplot(xlab = 'Categorias',main = paste("Grafico de barras de",var),
                                        col = brewer.pal(n = nlevels(Datos1[[var]]), name = "Blues"))
}
```

## Analisis descriptivo de variables en conjunto

```{r}
#| fig-aling: center
#| layout-ncol: 4
#| layout-nrow: 5

# Análisis descriptivo de vvaraibles en conjunto

for (i in 1:length(variables)-1){
  plot(Datos1[[i+1]],Datos1$estado_vital_5años,xlab=variables[i+1],ylab='estado_vital_5años',
       col=c("#99cc99", "#cc9999", "#9999cc"),main= paste("Mosaico variable estado_vital_5_años y ",
                                                          variables[i+1]))
 }
```


# Análisis de Supervivencia
