---
title: "Untitled"
lang: es
format: pdf
editor: visual
---

```{r}
#| label: Librerias
#| echo: false
#| message: false
#| warning: false
library(readxl)
library(janitor)
library(tidyverse)
library(magrittr)
library(DescTools)
library(kableExtra)
library(RColorBrewer)
library(viridis)
library(visdat)

library(survival)
library(ggfortify)
library(fastcox)
library(glmpath)
library(KMsurv)
library(survMisc)
library(survminer)
```

```{r}
#| echo: false

# cargando la base de datos
datos <- read_excel("BDD.Análisis_PD-L1_26-09-2024.xlsx")
datos %<>% clean_names() # limpiando los nombres de las variables
```

```{r}
#| echo: false

# datos$estado_vital_5anos %<>% as.factor()
datos$pd_l1 %<>% as.factor()
datos$ciudad %<>% as.factor()
datos$educacion %<>% as.factor()
datos$estrato %<>% as.factor()
datos$afiliacion %<>% as.factor()
datos$lateralidad_cat %<>% as.factor()
datos$tipo_histologico %<>% as.factor()
datos$grado_histologico %<>% as.factor()
datos$eur_cat %<>% as.factor()
datos$afr_cat %<>% as.factor()
datos$nam_cat %<>% as.factor()
datos$grado_nuclear %<>% as.factor()
datos$t %<>% as.factor()
datos$n %<>% as.factor()
datos$m %<>% as.factor()
datos$estadio %<>% as.factor()
datos$estadio_cat %<>% as.factor()
datos$er %<>% as.factor()
datos$pr %<>% as.factor()
datos$her2 %<>% as.factor()
datos$recaidas %<>% as.factor()
datos$subtipo_molecular_definitivo %<>% as.factor()
datos$interaccion_reg_stage %<>% as.factor()
```

# Análisis Exploratorio

```{r}
#| include: false
datos %>% dim()
```

La base de datos cuenta con 330 observaciones y 54 variables

```{r}
datos %>% count(estado_vital_5anos) %>% kable(align = 'cc')
```

Observamos que el numero de observaciones por muerte de cáncer de mama es bajo en comparación al numero de censuras es de 260.

```{r}
datos %>% 
```

```{r}
#| echo: false
sapply(datos, function(x) sum(is.na(x)))
```

```{r}
stats::chisq.test(datos$estado_vital_5anos, datos$afiliacion)
```

```{r}
cancer.km <- survfit(Surv(tiempo_evento_bx_5anos,estado_vital_5anos) ~ estadio_cat3
                     ,data = datos, type = "kaplan-meier")


cancer.km1 <- survfit(Surv(tiempo_supervivencia_dias,estado_vital_5anos) ~ 1, 
                     data = datos, type = "kaplan-meier")


summary(cancer.km)
```

```{r}
ggsurvplot(fit = cancer.km, data = datos, conf.int = T, 
           title = "Curva de Supervivencia", 
           xlab = "Tiempo", ylab = "Probabilidad de supervivencia",
           theme_bw)


ggsurvplot(fit = cancer.km1, data = datos, conf.int = T, 
           title = "Curva de Supervivencia", 
           xlab = "Tiempo", ylab = "Probabilidad de supervivencia", 
           legend.title = "Estimación", 
           legend.labs = "Kaplan-Meier")
```

```{r}
survdiff(Surv(tiempo_evento_bx_5anos,estado_vital_5anos) ~estadio_cat3, 
         data = datos, rho = 0) 
```

```{r}
coxph(Surv(tiempo_evento_bx_5anos,estado_vital_5anos) ~ edad+afiliacion+ciudad+eur+afr+nam+pr+estadio_cat, data = datos)
```

```{r}
cocktail(lambda = 1)
```

```{r}
tabla <- table(factor(datos$estado_vital_5anos), factor(datos$ciudad))
tabla
```

```{r}
cor(datos)
```

}
